ProjectLightSwitch/ProjectLightSwitch/Controllers/StoryPortalController.cs
using System;
using ProjectLightSwitch.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectLightSwitch.Attributes;

namespace ProjectLightSwitch.Controllers
{
    public class StoryPortalController : Controller
    {
        //
        // GET: /StoryPortal/

        public ActionResult Index()
        {
            return RedirectToAction("Browse");
        }

        [HttpGet]
        public ActionResult Browse([Bind(Include="SearchTerm,LanguageId")] StoryTypesViewModel searchModel)
        {
            StorySystem.PopulateStoryTypesViewModel(searchModel);
            return View(searchModel);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">The story response id that helped</param>
        /// <returns></returns>
        [AjaxOnly]
        [HttpPost]
        public ActionResult ThisHelped(int id)
        {
            return Content(StorySystem.ThisHelped(id) ? "true" : "false");
        }

        public ActionResult Search(StoryResponseSearchInputModel searchModel)
        {
            var model = StorySystem.SearchStoryResponses(searchModel);
            return View(model);
        }

        public ActionResult View(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction("Search");
            }
            var model = StorySystem.GetStoryResponseDetails(id.Value);
            if (model == null)
            {
                HelperFunctions.AddGlobalMessage(TempData, "That story could not be found.");
                return RedirectToAction("Search");
            }
            return View(model);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="storyType">Actually the <see cref="LocalizedStoryType.LocalizedStoryTypeId" /> to search for</param>
        /// <returns></returns>
        public ActionResult Create(int? id)
        {
            if (!id.HasValue || id.Value <= 0)
            {
                return RedirectToAction("Browse");
            }

            var model = new StoryResponseCreationViewModel();
            StorySystem.PopulateStoryResponseModelOutput(id.Value, ref model);

            if (model.StoryTypeResultModel == null)
            { 
                HelperFunctions.AddGlobalMessage(TempData, "An invalid story type was specified.");
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(StoryResponseCreationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var error = StorySystem.SaveStoryResponse(model);
                HelperFunctions.AddGlobalMessage(
                    TempData,
                    error ?? "Your story has been successfully saved.");
                return RedirectToAction("Index");
            }
            else
            {

                var errors = ModelState.Values.SelectMany(v => v.Errors);

                if (model == null || model.StoryTypeResultModel == null || model.StoryTypeResultModel.TranslatedStoryTypeId <= 0)
                {
                    return RedirectToAction("Index");
                }
                StorySystem.PopulateStoryResponseModelOutput(model.StoryTypeResultModel.TranslatedStoryTypeId, ref model);
                return View(model);
            }
        }
    }
}

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/Browse.cshtml
@model ProjectLightSwitch.Models.StoryTypesViewModel
@{
    ViewBag.Title = "Browse available story types";
}


<section>
    <h2>Search for Others' Stories</h2>
    @Html.ActionLink("View Responses", "Search", null, new { @class = "button1" })
    <div class="margin-large"></div>
    <h2>Share your Story</h2>
</section>
<section class="accent">
    <h3>Search for a Story Type</h3>
    @using (Html.BeginForm("Browse", "StoryPortal", null, FormMethod.Get))
    {
        @Html.LabelFor(t => t.SearchTerm)
        <span>: </span>
        @Html.EditorFor(t => t.SearchTerm)
        <input type="submit" value="Search" />
    }
</section>
<section>
        @if (!Model.StoryTypeViewModels.Any())
    { 
        if(!string.IsNullOrWhiteSpace(@Model.SearchTerm))
        {
            <p class="i">No story types containing &quot;@Model.SearchTerm&quot; were found.</p>
        }
        else
        {
            <p class="i">No story types have been created yet.</p>
        }
    }

    @for (int i = 0; i < Model.StoryTypeViewModels.Count(); i++)
    {
        var storyType = Model.StoryTypeViewModels.ElementAt(i);

        for (int j = 0; j < storyType.LocalizedStoryTypes.Count(); j++)
        {
            var localizedStoryType = storyType.LocalizedStoryTypes.ElementAt(j);
            <div class="story-type">
                <div class="b center">
                    @Html.ActionLink(localizedStoryType.Title, "Create", new { id = localizedStoryType.LocalizedStoryTypeId })
                </div>
                <h3>
                    @Html.LabelFor(m => m.StoryTypeViewModels.ElementAt(i).LocalizedStoryTypes.ElementAt(j).Description)
                </h3>
                <p>
                    @Html.DisplayFor(m => m.StoryTypeViewModels.ElementAt(i).LocalizedStoryTypes.ElementAt(j).Description)
                </p>
                <div>
                    <h3 class="nopadding nomargin">Story Tags</h3>
                    @if(Model.StoryTypeViewModels.ElementAt(i).Tags.Any())
                    {
                        <ul class="tagBreadcrumbs">
                            @foreach (var tag in Model.StoryTypeViewModels.ElementAt(i).Tags)
                            {
                                <li>@tag.text</li>
                            }
                        </ul>
                    }
                    else
                    {
                        <span class="i">There are no tags associated with this story type.</span>
                    }

                    @*Shouldn't be needed*@
                    <br class="clear" />
                </div>
            </div>
        }
    }
</section>

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/Create.cshtml
@model ProjectLightSwitch.Models.StoryResponseCreationViewModel
@{
    ViewBag.Title = "Write a Story";
}
@section head {
    @Scripts.Render("~/bundles/jqueryui")
}
@section scripts
{
    @Scripts.Render("~/Scripts/StoryWizard.js", "~/bundles/jqueryval")

    <script type="text/javascript" language="javascript">
        $(document).ready(function () {
                $('#gender').buttonset();
                //$('#age').spinner();

                var tagnav = new TagNavigator('#tagnav');
                var breadcrumbs = new SelectedTagBreadCrumbs($('#selectedTags'), tagnav, { cssPrefix: '', separator: ' > ', closable: true });
                //NavigateToStep(0);
        });

        

        var wizard = new StoryWizard('#storyWizard');
    </script>
}
<section>
    <h2>Tell Your Story</h2>
</section>
<section class="accent">
    @using (Html.BeginForm("Create", "StoryPortal", FormMethod.Post, new { id = "storyWizard" }))
    {
        <input type="hidden" name="StoryTypeResultModel.TranslatedStoryTypeId" value="@Model.StoryTypeResultModel.TranslatedStoryTypeId" />
        <section>
            <div class="right">@{ Html.RenderPartial("~/Views/StoryPortal/_StorySteps.cshtml", new ProjectLightSwitch.Models.StoryStepModel() { CurrentStep = 1, NumSteps = 3 }, null); }</div>
            <h2>@Model.StoryTypeResultModel.Title</h2>
            <p>@Model.StoryTypeResultModel.Description</p>

            @{ Html.RenderPartial("~/Views/StoryPortal/_PersonalInfoEntry.cshtml", Model, null); }
            <div class="right">
                <a href="#" class="next-section button2">Next</a>
            </div>
        </section>

        <section>
            <div class="right">@{ Html.RenderPartial("~/Views/StoryPortal/_StorySteps.cshtml", new ProjectLightSwitch.Models.StoryStepModel() { CurrentStep = 2, NumSteps = 3 }, null); }</div>
            @{ Html.RenderPartial("~/Views/StoryPortal/_StoryEntry.cshtml", Model, null);  }
            <div class="right">
                <a href="#" class="prev-section button2">Previous</a>
                <a href="#" class="next-section button2">Next</a>
            </div>
        </section>

        <section>
            <div class="right">@{ Html.RenderPartial("~/Views/StoryPortal/_StorySteps.cshtml", new ProjectLightSwitch.Models.StoryStepModel() { CurrentStep = 3, NumSteps = 3 }, null); }</div>
            @{ Html.RenderPartial("~/Views/StoryPortal/_AnswerEntry.cshtml", Model, null); }
            <div class="right">
                <a href="#" class="prev-section button2">Previous</a>
                <input class="next-section button2" type="submit" value="Submit Story" />
            </div>
        </section>
    }
</section>

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Story Portal</h2>
<ul>
    <li>@Html.ActionLink("View story types to available to answer", "Browse")</li>
</ul>

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/Search.cshtml
@model ProjectLightSwitch.Models.StoryResponseSearchViewModel
@{
    ViewBag.Title = "Search";
}

@section head {
@Scripts.Render("~/bundles/jqueryui")

<script type="text/javascript">

    var tagSearcher = null;

    $(document).ready(function () {
        tagSearcher = new TagSearcher($('#tag-searcher'));
        var breadcrumbs = new SelectedTagBreadCrumbs($('#selected-tags'), tagSearcher, { cssPrefix: '', separator: ' > ', closable: true });
        var acomplete = jQuery("#tag-autocomplete").autocomplete({
            source: function (request, response) {
                tagSearcher.tagAdapter.searchTags(request.term, function (data) {
                    for (var i = 0; i < data.length; i++)
                    {
                        var label = [];
                        var path = data[i].path;
                        for (var j= 0; j < path.length; j++)
                        {
                            label.push(path[j].text);
                        }
                        data[i].fullLabel = label.join(' > ');

                        label.splice(1, label.length - 3);
                        data[i].label = label.join(' > ');
                    }
                    response(data);
                });
            },
            minLength: 3,
            select: function (event, ui) {
                if (ui.item && ui.item.value){
                    tagSearcher.navigateToTag(ui.item.value, true);
                    ui.item.value= ui.item.fullLabel;
                } 
            },
            focus: function (event, ui) {
                $("#tag-autocomplete").val(ui.item.label);
                return false;
            }
        });

        // Init values

        // AGE 
        var minAge = '@Model.SearchParameters.MinAge' || 13;
        var maxAge = '@Model.SearchParameters.MaxAge' || 100;

        // initialize age
        $('#MinAge').val(minAge);
        $('#MaxAge').val(maxAge);
        $("#age-range-results").text(minAge + " to " + maxAge  + " yrs");

        $("#age-range").slider({
            range: true,
            min: 13,
            max: 100,
            values: [minAge, maxAge],
            slide: function (event, ui) {
                $('#MinAge').val(ui.values[0]);
                $('#MaxAge').val(ui.values[1]);
                $("#age-range-results").text(ui.values[0] + " to " + ui.values[1] + " yrs");
            }
        });

        // COUNTRY
        $('[name="Country"]').val('@Model.SearchParameters.Country');

        // GENDER
        @if(!string.IsNullOrWhiteSpace(Model.SearchParameters.Gender))
        {
            @:$('[name="Gender"]').val('@Model.SearchParameters.Gender');
        }
            
        // TAGS
        @foreach(var tagInfo in Model.SearchParameters.SelectedTagPaths)
        {
            @:tagSearcher.selectTagByPath(@(Html.Raw(tagInfo.Serialize())).path);
        }
    });

    function switchPage(page)
    {
        $('form#search').append($('<input>').attr('name','Page').val(page))
                        .trigger('submit');
    }
    
</script>

<style type="text/css">

#age-range {
    width: 75%;
    margin: 10px auto;
}

#age-range-results {
    color: blue;
}

#tag-browsing-pane {
    width:200px;
    min-height:200px;
    float:left;
        
}
#main-pane{
    min-height:200px;
    overflow:hidden;
}

.search-field-block {
    height: 50px;
    margin-left: 15px;
    display: inline-block;
    vertical-align: middle;
}

#sel-tag-bar > * {
    margin-top:0;
    margin-bottom:0;
    display: inline-block;
    vertical-align: middle;
}

.search-field-block h3 {
    padding: 0;
    margin: 0;
}

#selected-tags, #selected-tags .tagBreadcrumbs  {
    display: inline-block;
    border: none;
    background:none;
    padding:0;
    margin:0 10px 0 0;
}

#response-results {
    word-break: break-all;
}

.story-response-result .tagBreadcrumbs,
#selected-tags, #selected-tags .tagBreadcrumbs {
    display: inline-block;
    border: none;
    background:none;
}

#sel-tag-bar h3 {
    line-height:100%;
    vertical-align: middle;
}

.rating {
    color: gray;
    font-size: .8em;
    font-style: italic;
}

.story-response-result {
    border-bottom: 1px solid #a9a9a9;
    padding: 5px;
}

.story-response-result h3 {
    font-weight: bold;
    text-decoration: underline;

}

.ui-menu .ui-menu-item a{

    white-space: nowrap;
}

</style>
}

<section>
    <h2>Story Search:</h2>
    @using (Html.BeginForm("Search", "StoryPortal", FormMethod.Get, new { id = "search" }))
    {
        <div id="search-bar">
            <div class="search-field-block">
                <h3>Age Range: <span id="age-range-results"></span></h3>

                <input type="hidden" id="MinAge" name="MinAge" />
                <input type="hidden" id="MaxAge" name="MaxAge" />
                <div id="age-range"></div>
            </div>

            <div class="search-field-block">
                <h3>Gender:</h3>
                <select name="Gender">
                    <option selected="selected" value="">Any</option>
                    <option value="M">Male</option>
                    <option value="F">Female</option>
                    <option value="I">Intersex</option>
                </select>
            </div>

            <div class="search-field-block">
                <h3>Country:</h3>
                <select name="Country">
                    <option selected="selected" value="0">Any</option>
                    @{
        var countries = ProjectLightSwitch.Models.StorySystem.GetCountries();
        foreach (var country in countries)
        {
            <option value="@country.CountryId">@country.CountryName</option>
        }
                    }
                </select>
            </div>


            <div class="search-field-block">
                <h3>Tag Search:</h3>
                <input id="tag-autocomplete" class="full-width" type="search" />
            </div>

            <div class="search-field-block">
                <input type="submit" value="Search" class="button2" />
            </div>
        </div>

        <div id="sel-tag-bar">
            <h3 class="inline">My Tags:</h3>
            <div id="selected-tags"></div><br class="clear" />
        </div>

    <!-- Search Content and tag selection bar -->
        <table class="full-width">
            <tr>
                <td class="padding-large" style="vertical-align:top;width:200px;">
                    <h3>Browse Tags</h3>
                    <div id="tag-searcher"></div>
                </td>
                <td class="padding-large" style="vertical-align:top">
                    <div id="main-pane">
                        <h3>Results</h3>
                        <div id="response-results">
                            @if (!Model.Results.Any())
                            {
                                <span class="i b">No results were found.</span>
                            }
                            else
                            {

                                foreach (var result in Model.Results)
                                {
                                    <div class="story-response-result">
                                        @Html.ActionLink(result.StoryResponse.Title, "View", new { id = result.StoryResponse.StoryResponseId }, new { @class = "b i" })
                                        <p class="i" style="color:gray">@result.RecentRating @(result.RecentRating == 1 ? "person" : "people") recently found this useful.</p>
                                        <p>@result.StoryResponse.Story</p>
                                        @if (result.Tags.Any())
                                        {
                                            <ul class="tagBreadcrumbs">
                                                @foreach (var tag in result.Tags)
                                                {
                                                    <li>
                                                        <span title="@tag.FullPathLabel">
                                                            @tag.AbbreviatedPathLabel
                                                        </span>
                                                    </li>
                                                }
                                            </ul>
                                        }
                                    </div>
                                }

                                if (Model.Results.Any())
                                {
                                    <div id="paging">
                                        Page:
                                        @{
                                    int numPages = (int)(Math.Ceiling((decimal)Model.TotalResultCount / (decimal)Model.SearchParameters.ResultsPerPage));
                                        }

                                        @for (int i = 0; i < numPages; i++)
                                        {
                                            if (i == Model.SearchParameters.Page)
                                            {
                                                <b>@(i + 1)</b>
                                            }
                                            else
                                            {
                                                <a href="#" onclick="switchPage(@i;return false;">@(i + 1)</a>
                                            }
                                        }
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </td>
            </tr>
        </table>


       
    }
</section>

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/View.cshtml
@model ProjectLightSwitch.Models.StoryResponseDetailsModel

@{
    ViewBag.Title = "View";
}

@section head { 
<style type="text/css">
    #story-container {
        padding: 10px;
    }
    #story-container > #story-content {
        float:left;
        width: 70%;
        word-break: break-all;
    }
    #story-container > #related-content {
        float:right;
        width:30%;
    }
</style>

<script type="text/javascript">
    function thisHelped() {
        $.ajax({
            cache: true,
            data: { 'id': '@Model.Response.StoryResponseId' },
            url: '@Url.Action("ThisHelped", "StoryPortal")',
            type: "POST"
        }).success(function (response) {
            $('#this-helped').hide();
            $('#this-helped-label').show();
        });
    }
</script>
}
<section>
    <div id="story-container">
        <div id="story-content">
            <h1>@Model.Response.Title</h1>
            <h3 class="inline">Story Tags: </h3>
            <div>
                @if (Model.Tags != null && Model.Tags.Any())
                {
                    <ul class="tagBreadcrumbs">
                        @foreach (var tag in Model.Tags)
                        {
                            <li title="@tag.FullPathLabel">@tag.AbbreviatedPathLabel</li>
                        }
                    </ul>
                }
                else
                {
                    <p>This story is not tagged.</p>
                }
            </div>
            <h3>About Me:</h3>
            <p class="personal-description">
                I am a @Model.Response.Age year old
                @(ProjectLightSwitch.Models.Enums.EnumExtensions.ParseGender(Model.Response.Gender))
                from @(Model.Response.Country.Country1).
            </p>

            <h3>My Story:</h3>
            <p>@Model.Response.Story</p>

            <h3>Questions and Answers:</h3>
            @foreach (var ans in Model.Response.Answers)
            {
                <p><b>@ans.Question.Prompt</b></p>
                <p>@ans.AnswerText</p>
            }

            <h3>Did you find this story helpful?</h3>
            <a id="this-helped" href="#" class="button2" onclick="thisHelped();return false;">Let us Know</a>
            <span id="this-helped-label" style="display:none;">Thank you for sharing your opinion about this story.</span>
        </div>
        <div id="related-content">
            <div class="right margin">
                @Html.ActionLink("Back To Search", "Search", null, new { @class="button1" })
            </div>

            <h3 class="margin-medium">Similar Stories</h3>
            @if (Model.RelatedResponses.Any())
            {
                foreach (var relatedResponse in Model.RelatedResponses)
                {
                    <div>
                        <h3>@Html.ActionLink(relatedResponse.Title, "View", new {id=relatedResponse.StoryResponseId})</h3>
                        <span class="personal-description">
                            I am a @relatedResponse.Age year old
                            @(ProjectLightSwitch.Models.Enums.EnumExtensions.ParseGender(relatedResponse.Gender))
                            from @relatedResponse.Country.Country1
                        </span>
                        <p>
                            @(relatedResponse.Story.Substring(0, Math.Min(relatedResponse.Story.Length, 150)) + "...")
                        </p>
                    </div>
                }
            }
            else
            {
                <i>No similar stories were found.</i>
            }
        </div>
        <br class="clear" />
    </div>
</section>

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/_AnswerEntry.cshtml
@model ProjectLightSwitch.Models.StoryResponseCreationViewModel
<h3>@ProjectLightSwitch.Views.StoryPortal.StoryResources.Part3Header</h3>
@for (int i = 0; i < Model.StoryQuestions.Count(); i++)
{
    <h4 class="nopadding nomargin">@Model.StoryQuestions.ElementAt(i).Prompt</h4>
    <textarea name="StoryAnswers[@Model.StoryQuestions.ElementAt(i).QuestionId]" class="full-width" data-rule-required="true" cols="50" rows="3"></textarea>
}

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/_PersonalInfoEntry.cshtml
@model ProjectLightSwitch.Models.StoryResponseCreationViewModel
<h3>@ProjectLightSwitch.Views.StoryPortal.StoryResources.Part1Header</h3>
<table class="input-form">
    <tr>
        <td>Age:</td>
        <td>
            <input type="text" id="age" name="age" data-rule-required="true" data-rule-min="13" data-rule-max="150" />
        </td>
    </tr>
    <tr>
        <td>Gender:</td>
        <td>
            <div id="gender">
                <input type="radio" id="radioM" name="gender" value="M" data-rule-required="true"><label for="radioM">@ProjectLightSwitch.Views.StoryPortal.StoryResources.Male</label>
                <input type="radio" id="radioF" name="gender" value="F"><label for="radioF">@ProjectLightSwitch.Views.StoryPortal.StoryResources.Female</label>
                <input type="radio" id="radioI" name="gender" value="I"><label for="radioI">@ProjectLightSwitch.Views.StoryPortal.StoryResources.Intersex</label>
            </div>
        </td>
    </tr>
    <tr>
        <td>Country:</td>
        <td>
            <select name="country" data-rule-min="1">
            @foreach (var lang in Model.CountryListItems)
            { 
                <option value="@lang.Value">@lang.Text</option>
            }
            </select>
    </tr>
</table>

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/_StoryEntry.cshtml
@model ProjectLightSwitch.Models.StoryResponseCreationViewModel
@{ var minStoryLength = "30"; }
<h3>@ProjectLightSwitch.Views.StoryPortal.StoryResources.Part2Header</h3>

<table class="full-width">
    <tr>
        <td style="width:100px">Story Title:</td>
        <td><input type="text" name="StoryTitle" class="full-width"  data-rule-required="true" /></td>
    </tr>
    <tr>
        <td style="width:100px">Story:</td>
        <td><textarea name="StoryResponse" rows="8" cols="50" class="full-width" data-rule-required="true" data-rule-minlength="@minStoryLength"></textarea></td>
    </tr>
    <tr>
        <td style="width:100px">Tags:</td>
        <td><div id="tagnav"></div><br class="clear" /></td>
    </tr>
    <tr>
        <td style="width:100px">Selected Tags:</td>
        <td><div id="selectedTags"></div><br class="clear" /></td>
    </tr>
</table>

ProjectLightSwitch/ProjectLightSwitch/Views/StoryPortal/_StorySteps.cshtml
@model ProjectLightSwitch.Models.StoryStepModel
@* Requires .steps{} style in Site_Custom.css *@
<div class="steps float-right">
    @for (int i = 1; i <= Model.NumSteps; i++)
    {
        if (i == Model.CurrentStep)
        {
            <span class="sel">@i</span>
        }
        else
        {
            <span>@i</span>
        }
    }
</div>