ProjectLightSwitch/ProjectLightSwitch/Models/Generated/Tag.cs
namespace ProjectLightSwitch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("pls.Tags")]
    public partial class Tag
    {
        public Tag()
        {
            Descendants = new HashSet<TagTree>();
            Ancestors = new HashSet<TagTree>();
            TranslatedTags = new HashSet<TranslatedTag>();
            StoryResponses = new HashSet<StoryResponse>();
            StoryTypes = new HashSet<StoryType>();
        }
        [DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int TagId { get; set; }

        public byte TagType { get; set; }

        public virtual ICollection<TagTree> Descendants { get; set; }

        public virtual ICollection<TagTree> Ancestors { get; set; }

        public virtual ICollection<TranslatedTag> TranslatedTags { get; set; }

        public virtual ICollection<StoryResponse> StoryResponses { get; set; }

        public virtual ICollection<StoryType> StoryTypes { get; set; }
    }
}

ProjectLightSwitch/ProjectLightSwitch/Models/Tag.cs
namespace ProjectLightSwitch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("pls.Tags")]
    public partial class Tag
    {
        public Tag()
        {
            TagsTranslateds = new HashSet<TagsTranslated>();
            Ancestors = new HashSet<TagTree>();
            Descendants = new HashSet<TagTree>();
            Surveys = new HashSet<Survey>();
        }

        public int TagId { get; set; }

        public byte TagType { get; set; }

        [Required]
        [StringLength(1024)]
        public string EnglishText { get; set; }

        public virtual ICollection<TagsTranslated> TagsTranslateds { get; set; }

        public virtual ICollection<TagTree> Ancestors { get; set; }

        public virtual ICollection<TagTree> Descendants { get; set; }

        public virtual ICollection<Survey> Surveys { get; set; }
    }
}

ProjectLightSwitch/ProjectLightSwitch/Areas/SiteAdmin/Controllers/TagsController.cs
using System;
using ProjectLightSwitch.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectLightSwitch.Areas.SiteAdmin.Controllers
{
    [Authorize(Roles = SiteSettings.AdminRole)]
    public class TagsController : Controller
    {
        //
        // GET: /SiteAdmin/Tags/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit(int tagid)
        {
            if (tagid == TagTree.InvisibleRootId || TagSystem.GetTag(tagid) == null)
            {
                return RedirectToAction("Index");
            }
            return View(TagSystem.GetTagOutputViewModel(tagid));
        }

        [HttpPost]
        public ActionResult Rename(TagViewModel model)
        {
            if (
                model.Tag != null
                && !string.IsNullOrWhiteSpace(model.EnglishText)
                && model.Tag.TagId != TagTree.InvisibleRootId
                && ModelState.IsValid)
            {
                TagSystem.EditTag(model.Tag.TagId, model.TranslationsWithIntKeys);
                HelperFunctions.AddGlobalMessage(TempData, "Tag updated.");
            }
            else
            {
                HelperFunctions.AddGlobalMessage(TempData, "Error updating tag.");
            }
            return RedirectToAction("Edit", new { tagid = model.Tag != null ? model.Tag.TagId : 0 });
        }

        [HttpPost]
        public ActionResult Remove(int tagid)
        {
            if (tagid == TagTree.InvisibleRootId)
            {
                return RedirectToAction("Index");
            }

            // Where to return after deletion
            var parent = TagSystem.GetParent(tagid);

            if (parent == null)
            {
                HelperFunctions.AddGlobalMessage(TempData, "Ancestor doesn't exist");
                return RedirectToAction("Index");
            }

            bool success = TagSystem.RemoveTag(tagid);
            string message = success 
                ? "The tag and its descendants were all removed." 
                : "An error occurred while attempting to delete this tag.";
            HelperFunctions.AddGlobalMessage(TempData, message);
            return RedirectToAction("Index", new { tagid = parent.TagId });
        }

        [HttpPost]
        public ActionResult AddChildren(List<TagViewModel> model)
        {
            model.RemoveAll(m => string.IsNullOrWhiteSpace(m.EnglishText));
            int numAdded = (model.Count > 0) ? TagSystem.AddTags(model) : 0;
            string message = string.Format("{0} of {1} tags were added.", numAdded, model.Count);
            HelperFunctions.AddGlobalMessage(TempData, message);
            return RedirectToAction("Index", model.Count > 0 && model[0].Tag != null ? new { tagid = model[0].Tag.TagId } : null);
        }
    }

}

ProjectLightSwitch/ProjectLightSwitch/Controllers/TagsController.cs
using ProjectLightSwitch.Attributes;
using ProjectLightSwitch.Models;
using ProjectLightSwitch.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectLightSwitch.Controllers
{
    
    public class TagsController : Controller
    {
        //
        // GET: /Descendants/
        public ActionResult Index()
        {
            return View();
        }

        // TODO: make partial
        //public ActionResult TagNavigator()
        //{
        //    return PartialView("~/Views/Shared/_TagNavigator.cshtml", TagSystem.GetCategories());
        //}

        //[AjaxOnly]
        [OutputCache(Duration = 30, VaryByParam = "*", VaryByHeader = "Accept-Language")]
        public ActionResult Navigate(int id, bool childrenOnly = false, int language = Language.DefaultLanguageId)
        {
            return Content(TagSystem.GetFullTagNavigationPath_Json(id, childrenOnly, language), "application/json");
        }

        //[AjaxOnly]
        [HttpGet]
        public ActionResult Search(string term)
        {
            var result = TagSystem.GetPaths_Json(TagTree.InvisibleRootId, term, true, Language.DefaultLanguageId);
            return Content(result, "application/json");
        }

        //[AjaxOnly]
        //public ActionResult AddChildTag(int tagid, string text, byte storyType, int languageId = Language.DefaultLanguageId)
        //{
        //    if(!Enum.IsDefined(typeof(TagType), storyType) || storyType == TagTree.InvisibleRootId)
        //    {
        //        return Content("{'error':'Invalid Type.'}", "application/json");
        //    }

        //    using (var context = new StoryModel())
        //    {
        //        var tagType = (TagType)storyType;

        //        TagSystem.AddTag(new Ancestor() { TagType = storyType }, tagid);
        //        TagSystem.AddTag(storyType, tagid, 

        //        var item = context.Tags.Where(t => t.TagId == storyType && t.TagId != TagTree.InvisibleRootId).FirstOrDefault();
        //        if (item != null)
        //        {
        //            context.Tags.Remove(item);
        //            bool success = context.SaveChanges() > 0;
        //            return Json(new { result = success, error = success ? null : "There was an error removing the tag." });
        //        }
        //        return Content("{'error':'Descendants not found.'}", "application/json");
        //    }
        //}

    //    public ActionResult RemoveTag(int TagId)
    //    {
    //        var parent = TagSystem.GetParent(TagId);
    //        string message = TagSystem.RemoveTag(TagId) ? "Ancestor and all child tags removed." : "There was an error removing the tag";
    //        HelperFunctions.AddGlobalMessage(TempData, message);
    //        return RedirectToAction("Index", (parent != null) ? new { id = parent.TagId } : null);
    //    }

    //    public ActionResult AddChildTags(List<TagViewModel> inputModel)
    //    {
    //        var childrenToAdd = new List<TagViewModel>(inputModel);

    //        inputModel.RemoveAll(m => string.IsNullOrWhiteSpace(m.EnglishText));

    //        if (inputModel.Count > 0 && ModelState.IsValid)
    //        {
    //            foreach(var child in inputModel)
    //            {
    //                //don't add tags with no english tag
    //                if (String.IsNullOrWhiteSpace(child.Translations[Language.DefaultLanguageId]))
    //                { 
    //                    childrenToAdd.Remove(child);
    //                    HelperFunctions.AddGlobalMessage(TempData, "A tag could not be added because it lacked an English name.");
    //                    continue;
    //                }
    //            }

    //            return RedirectToAction("Index", new { id = inputModel.First().ParentId });
    //        }

    //        return RedirectToAction("Index");
    //    }
    }
}

ProjectLightSwitch/ProjectLightSwitch/Areas/SiteAdmin/Views/Tags/Edit.cshtml
@model ProjectLightSwitch.Models.TagViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Edit";
    int initialChildBoxes = 6;
}

@section head {

    @Styles.Render("~/Content/tagnav")
    @Scripts.Render("~/bundles/tags")
    @Scripts.Render("~/bundles/jqueryui")
}

@section scripts{
    <script type="text/javascript" language="javascript">
        $(document).ready(function () {
            var tagnav = new TagNavigator('#tagnav', {
                enabled: false,
                editUrlFormat: '@Url.Action("Edit", "Tags", new { area = "SiteAdmin", tagid = "(tagid)" }).Replace("(tagid)", "{0}")',
            });
            $('.tag-type').buttonset();
        });
    </script>
}
<section>
    <h2>Edit Tag </h2>
    @Html.ActionLink("Go Back", "Index", new { id = Model.Tag.TagId })

    <section class="tag-section">
        <h3>Currently Selected Tag: <u>@Model.Translations[ProjectLightSwitch.Models.Language.DefaultLanguageId.ToString()]</u></h3>
        <div id="tagnav"></div>
    </section>

    @using (Html.BeginForm("Rename", "Tags", new { area = "SiteAdmin" }, FormMethod.Post))
    {
        <section class="tag-section">
            <h3>Change Name</h3>
            @Html.HiddenFor(m => m.Tag.TagId)
            @Html.HiddenFor(m => m.Tag.TagType)
            <div id="addTextContainer">
                <table>
                    @foreach (var lang in Model.Languages)
                    {
                        <tr>
                            <td>
                                @lang.Description:
                            </td>
                            <td>
                                @{
                        //string text;
                        //Model.Translations.TryGetValue(lang.LanguageId, out text);
                        var attrs = lang.LanguageId == ProjectLightSwitch.Models.Language.DefaultLanguageId
                            ? new Dictionary<string, object>()
                                {
                                    { "class", "b" }, { "data-rule-required", "true" }
                                }
                    : null;

                        if (!Model.Translations.ContainsKey(lang.LanguageId.ToString()))
                        {
                            Model.Translations[lang.LanguageId.ToString()] = string.Empty;
                        }

                                }
                                @Html.TextBoxFor(m => m.Translations[lang.LanguageId.ToString()], attrs)
                            </td>
                        </tr>
                    }
                    <tr>
                        <td colspan="2">
                            <input type="submit" class="full-width" value="Update Tag Names">
                        </td>
                    </tr>
                </table>
            </div>
        </section>
    }

    @* Can this tag have children?*@
    @if (Model.Tag.TagType == (byte)ProjectLightSwitch.Models.Enums.TagType.Category || Model.Tag.TagType == (byte)ProjectLightSwitch.Models.Enums.TagType.NavigationalTag)
    {
        using (Html.BeginForm("AddChildren", "Tags", new { area = "SiteAdmin" }, FormMethod.Post))
        {
            <section class="tag-section">
                <h3>Add Children</h3>
                <table id="addTextContainer">
                    <thead>
                        <tr>
                            <th>Tag Type</th>
                            <th>English Text</th>
                        </tr>
                    </thead>

                    @for (int i = 0; i < initialChildBoxes; i++)
                    {
                        <tr>
                            <td>
                                @Html.Hidden("model[" + i + "].Tag.TagId", Model.Tag.TagId)
                                <div class="tag-type">
                                    <input type="radio" id="tt_@(i)_sel" name="model[@i].Tag.TagType" value="@((int)ProjectLightSwitch.Models.Enums.TagType.SelectableTag)" checked />
                                    <label for="tt_@(i)_sel">Selectable tag</label>
                                    <input type="radio" id="tt_@(i)_nav" name="model[@i].Tag.TagType" value="@((int)ProjectLightSwitch.Models.Enums.TagType.NavigationalTag)" />
                                    <label for="tt_@(i)_nav">Navigational tag</label>
                                </div>
                            </td>
                            <td>
                                @Html.TextBox("model[" + i + "].EnglishText")
                            </td>
                        </tr>
                    }
                    <tr>
                        <td colspan="2"><input class="full-width" type="submit" value="Add children" /></td>
                    </tr>
                </table>
            </section>
        }
    }
    @using (Html.BeginForm("Remove", "Tags", new { area = "SiteAdmin" }, FormMethod.Post))
    {
        <section class="tag-section">
            <h3>Delete Tag</h3>
            @Html.Hidden("TagId", Model.Tag.TagId)
            <input type="submit" value="DELETE THIS TAG" onclick="return confirm('Do you really want to delete this tag?')" />
        </section>
    }
</section>

ProjectLightSwitch/ProjectLightSwitch/Areas/SiteAdmin/Views/Tags/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Tag Management";
}


@section head {
    @Styles.Render("~/Content/tagnav")
    @Scripts.Render("~/bundles/tags")
}

@section scripts
{
    <script type="text/javascript" language="javascript">
    @{ 
        string editUrl = Url.Action("Edit", "Tags", new { area = "SiteAdmin", tagid = "(tagid)" }).Replace("(tagid)", "{0}");
    }
    var tagnav = new TagNavigator('#tagnav', {
            enabled:true,
            editUrlFormat: '@editUrl',
            selectedTagSubmissionName: "SelectedTags[(0)]",
            ajax_navigateToTagUrl: '@Url.Action("Navigate", "Tags", new { area = "" })'
        });
    </script>
}
<section>
    <h2>Tag Management</h2>
    @using (Html.BeginForm("AddChildren", "Tags", new { area = "SiteAdmin" }, FormMethod.Post))
    {
        <h3>Add Category</h3>
        @Html.Hidden("model[0].Tag.TagId", ProjectLightSwitch.Models.TagTree.InvisibleRootId)
        @Html.Hidden("model[0].Tag.TagType", (byte)ProjectLightSwitch.Models.Enums.TagType.Category)
        <label>Category Name: <input name="model[0].EnglishText" /></label>
        <input type="submit" value="Add Category" />
    }

    @if(false)
    {
        <h3>Pending Tags</h3>
        <p>
            @Html.ActionLink("Review Pending Tags", "ReviewPending", new { area = "SiteAdmin" })
        </p>
    }

    <h3>Current Tags</h3>
    <form action="#" method="post">
        <div id="tagnav"></div>
    </form>
</section>