ProjectLightSwitch/ProjectLightSwitch/Areas/SiteAdmin/Controllers/StoryTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectLightSwitch.Models;
using System.Transactions;


namespace ProjectLightSwitch.Areas.SiteAdmin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class StoryTypeController : Controller
    {

        public ActionResult Index(StoryTypesViewModel model)
        {
            StorySystem.PopulateStoryTypesViewModel(model);
            return View(model);
        }

        public ActionResult Create(int Language = Language.DefaultLanguageId, int StoryTypeId = 0)
        {
            var model = new StoryTypeCreationModel();
            model.LanguageId = Language;
            model.StoryTypeId = StoryTypeId;
            return View(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(StoryTypeCreationModel model)
        {
            if (ModelState.IsValid)
            {
                var response = StorySystem.CreateStoryType(model);
                var message = response ?? "Story storyType created";
                HelperFunctions.AddGlobalMessage(TempData, message);
                return RedirectToAction("Index");
            }
            HelperFunctions.AddGlobalMessage(TempData, "Invalid input");
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var model = new LocalizedStoryTypeViewModel();
            StorySystem.PopulateLocalizedStoryTypeModel(id, model);
            if (model.LocalizedStoryType != null)
            {
                return View(model);
            }
            else
            {
                HelperFunctions.AddGlobalMessage(TempData, "An Invalid story storyType was supplied.");
                return RedirectToAction("Index");
            }
        }
        public ActionResult View(string search, int id = 0)
        {
            int languageId = Language.DefaultLanguageId;
            Tag tag = TagSystem.GetTag(id);
            int catId = (tag == null) ? 0 : tag.TagId;
            var paths = TagSystem.GetPaths(catId, search, true, languageId);
            ViewBag.Category = tag;
            return View(paths);
        }

        //public ActionResult AddChildTag(int category, int id = 0)
        //{
        //    // Hard coded for now
        //    TagSystem.AddTag(
        //        new Ancestor { EnglishText = Guid.NewGuid().ToString(), TagType = (byte)ProjectLightSwitch.Models.Enums.TagType.SelectableTag }, id);

        //    ViewBag.Message = "Descendants Added";
        //    return RedirectToAction("View", new { id = category });
        //}

        [HttpPost]
        public ActionResult DeleteStoryType(int id)
        {
            bool result = StorySystem.DeleteStoryType (id);
            ViewBag.Message = result ? "The story type was deleted" : "The selected story type was not found.";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteLocalizedStoryType(int id)
        {
            bool result = StorySystem.DeleteLocalizedStoryType(id);
            ViewBag.Message = result ? "The story type translation was deleted" : "The selected story type translation was not found.";
            return RedirectToAction("Index");
        }

        //public ActionResult RemoveTag(int category, int id)
        //{
        //    bool result = TagSystem.RemoveTag(id);
        //    ViewBag.Message = result ? "Descendants was deleted" : "Descendants could not be deleted";
        //    return RedirectToAction("View", new { id = category });
        //}
    }
}

ProjectLightSwitch/ProjectLightSwitch/Areas/SiteAdmin/Views/StoryType/Create.cshtml
@model ProjectLightSwitch.Models.StoryTypeCreationModel

@{
    ViewBag.Title = "Create a Story Type";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

@section head {
    @Styles.Render("~/Content/tagnav")
    @Scripts.Render("~/bundles/tags")
}

@section scripts {

    <script language="javascript" type="text/javascript">
        var questionPrompt = 'Add a Question:';

        $(document).ready(function () {
            (function () {
                var tagnav = new TagNavigator('#tagnav', { });
                var breadcrumbs = new SelectedTagBreadCrumbs($('#selectedTags'), tagnav, { cssPrefix: '', separator: ' > ', closable: true });

                var numInitialQuestions = 3;
                for (var i = 0; i < numInitialQuestions; i++) {
                    AddQuestionRow('questions');
                }
            })();
        });

        
        var NumRows = 0;
        function AddQuestionRow(tableId) {
            $('<tr>').append(
                $('<td>').text(questionPrompt)
            ).append(
                $('<td>').append(
                    $('<input>').attr('name', 'Questions[' + NumRows + ']'))
            ).appendTo($('#' + tableId));
            NumRows++;
        }
    </script>
}
<section>
    <h2>Write Your Story</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.HiddenFor(m => m.StoryTypeId)
        @Html.HiddenFor(m => m.LanguageId)

        <fieldset>
            <legend>StoryType</legend>
            <div class="editor-label">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Title, new { @class = "full-width" })
                @Html.ValidationMessageFor(model => model.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.Description, new { @class = "full-width", cols = "50", rows = "8" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>

            <table id="questions"></table>
            <input type="button" value="Add another question" onclick="AddQuestionRow('questions');" />

            @if (Model.StoryTypeId == 0)
            {
                <h3>Associated tags</h3>
                <div id="tagnav"></div>
                <h4>Current Tags:</h4>
                <div id="selectedTags"></div>
            }
        </fieldset>

        <p>
            <input type="submit" value="Create" class="button2" />
        </p>
    }
</section>

ProjectLightSwitch/ProjectLightSwitch/Areas/SiteAdmin/Views/StoryType/Details.cshtml
@model ProjectLightSwitch.Models.LocalizedStoryTypeViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Details";
}

@section head {
    @Styles.Render("~/Content/tagnav")
}

<section>
    @Html.ActionLink("Go Back", "Index")

    <h2>@Html.DisplayFor(m => m.LocalizedStoryType.Title)</h2>
    <h3>@Html.LabelFor(m => m.LocalizedStoryType.Description)</h3>
    <p>@Html.DisplayFor(m => m.LocalizedStoryType.Description)</p>

    <h3>@Html.LabelFor(m => m.LocalizedStoryType.Language.Description)</h3>
    <p>@Html.DisplayFor(m => m.LocalizedStoryType.Language.Description)</p>

    <h3>Questions</h3>
    <ol>
        @for (int i = 0; i < Model.LocalizedStoryType.Questions.Count; i++)
        {
            <li>
                @Model.LocalizedStoryType.Questions.ElementAt(i).Prompt
            </li>
        }
    </ol>

    <h3>Tags</h3>
    <ul class="tagBreadcrumbs">
        @foreach (var tag in Model.Tags)
        {
            <li>@tag.text</li>
        }
    </ul>

</section>

ProjectLightSwitch/ProjectLightSwitch/Areas/SiteAdmin/Views/StoryType/Index.cshtml
@model ProjectLightSwitch.Models.StoryTypesViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Story Type Management";
    var languages = ProjectLightSwitch.Models.TagSystem.GetLanguages();

}

@section head {
    @Styles.Render("~/Content/tagnav");
   
}

<section>
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class="button1" })
    </p>
    @foreach (var storyType in Model.StoryTypeViewModels)
    {
        <div class="story-type" id="@storyType.StoryTypeId">
            <h2 class="inline">
                Story Type #@storyType.StoryTypeId
            </h2>
            @using (@Html.BeginForm("DeleteStoryType", "StoryType", FormMethod.Post, new { @class = "inline" }))
            {
                @Html.Hidden("id", storyType.StoryTypeId);
               <input type="submit" class="button2" value="Delete" onclick="return confirm('Are you sure you want to delete this story type, all translations, questions, and answers?');" />
            }
            <p class="i">Created on: @(storyType.DateCreated.ToShortDateString())</p>
            @* Add translations when there's time *@
            @*Html.ActionLink("Create Translation", "Edit", new { disabled = "disabled", id = storyType.StoryTypeId }) | *@
            @*Html.ActionLink("Details", "Details", new { id = storyType.StoryTypeId }) | *@

            <div>
                <h3>Associated Tags:</h3>
                <ul class="tagBreadcrumbs">
                    @foreach (var tag in storyType.Tags)
                    {
                        <li>@tag.text</li>
                    }
                </ul>
                <br class="clear" />
            </div>
            <h3>Translations:</h3>
            <table border="1" cellpadding="4" cellspacing="0">
                <thead>
                    <tr>
                        <th>Actions</th>
                        <th>Language</th>
                        <th>Title</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var localizedStory in storyType.LocalizedStoryTypes)
                    {
                        <tr class="localized-story-type">
                            <td>
                                @using (@Html.BeginForm("DeleteLocalizedStoryType", "StoryType", FormMethod.Post, new { @class = "inline" }))
                                {
                                    @Html.Hidden("id", localizedStory.LocalizedStoryTypeId);
                                    <input type="submit" class="button2" value="Delete" onclick="return confirm('Are you sure you want to delete this story type translation and its questions and all answers?');" />
                                }
                            </td>
                            <td>
                                @languages.Where(l => l.LanguageId == localizedStory.LanguageId).Select(l => l.Description).FirstOrDefault()
                            </td>
                            <td>
                                <h3 class="inline">@Html.ActionLink(@localizedStory.Title, "Details", new { id = localizedStory.LocalizedStoryTypeId })</h3>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</section>